const SCREENS = {
  LOGIN: 'login',
  REGISTER: 'register',
  HOME: 'HOME',
  BOOKING: 'BOOKING',
  ORDER_SCREEN: 'ORDER_SCREEN',
  BOOKING_SCREEN: 'BOOKING_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
  DIRECTION_SCREEN: 'DIRECTION_SCREEN',
  MAP_SEARCH_SCREEN: 'MAP_SEARCH_SCREEN',
  ORDER_BOOKING_SCREEN: 'ORDER_BOOKING_SCREEN',
  PLACE_SEARCH_SCREEN: 'PLACE_SEARCH_SCREEN',
  SEARCH_FAST_SCREEN: 'SEARCH_FAST_SCREEN',
};

export default SCREENS;
